media:
  input: "assets/uploads"
  output: "/assets/uploads"
  extensions: [png, jpg, jpeg, webp, svg]

content:
  - name: site
    label: Page d’accueil
    type: file
    path: "content/site.json"
    fields:
      - { name: title, label: Titre, type: string }
      - { name: subtitle, label: Introduction, type: text }
      - name: badges
        label: Badges
        type: list
        fields:
          - { name: label, label: Badge, type: string }

  - name: paiement
    label: Page Paiement
    type: file
    path: "content/paiement.json"
    fields:
      - { name: title, label: Titre, type: string }
      - { name: intro, label: Intro, type: text }

      - name: bloc_form
        label: Bloc 1 — Formulaire (adresse / don / RIB)
        type: object
        fields:
          - { name: title, label: Titre, type: string }
          - { name: text, label: Texte, type: text }
          - { name: google_forms_embed_url, label: URL Google Forms (embed), type: string }
          - { name: iframe_height, label: Hauteur iframe, type: number }

      - name: bloc_lydia
        label: Bloc 2 — Lydia
        type: object
        fields:
          - { name: title, label: Titre, type: string }
          - { name: text, label: Texte, type: text }
          - { name: handle, label: Pseudo Lydia, type: string }
          - { name: link, label: Lien Lydia (optionnel), type: string, required: false }

      - name: bloc_wero
        label: Bloc 3 — Wero
        type: object
        fields:
          - { name: title, label: Titre, type: string }
          - { name: text, label: Texte, type: text }

      - name: bloc_cb
        label: Bloc 4 — Carte bancaire (HelloAsso)
        type: object
        fields:
          - { name: title, label: Titre, type: string }
          - { name: text, label: Texte, type: text }
          - { name: note, label: Note (contribution facultative), type: text }
          - { name: helloasso_link, label: Lien HelloAsso, type: string }
          - { name: button_text, label: Texte bouton, type: string }

  - name: produits
    label: Produits
    type: file
    path: "content/produits.json"
    fields:
      - name: items
        label: Liste des produits
        type: list
        fields:
          - { name: order, label: Ordre, type: number }
          - { name: title, label: Titre, type: string }
          - { name: price, label: Montant indicatif, type: string }
          - { name: description, label: Description, type: text }
          - { name: image, label: Image, type: image, required: false }
